[package]
name = "axiomatik-web"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.8", features = ["multipart"] }
tokio = { version = "1.49", features = ["full"] }
tower-http = { version = "0.6.8", features = ["fs", "trace"] }
askama = { version = "0.15" }
uuid = { version = "1.19", features = ["v4"] }
chrono = "0.4.42"
axum-extra = { version = "0.12.5", features = ["cookie"] }
serde = { version = "1.0.228", features = ["derive"] }
surrealdb = { version = "2.4.0", features = ["kv-rocksdb", "protocol-ws", "rustls"] }
bcrypt = "0.17.1"
