[package]
name = "axiomatik-web"
version = "0.1.0"
edition = "2024"

[dependencies]
[dependencies]
axum = { version = "0.8.1", features = ["multipart"] }
tokio = { version = "1.0", features = ["full"] }
tower-http = { version = "0.6.2", features = ["fs", "trace"] }
askama = { version = "0.12" }
uuid = { version = "1.0", features = ["v4"] }
